spring:
  application:
    name: order
  security:
    user:
      name: joshua
      password: joshua
server:
  port: 8083
logging:
  level:
    com.whoppr.*: ERROR
    org.mongodb.*: ERROR
    org.springframework.*: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://joshua:joshua@localhost:8761/eureka/
