spring:
  application:
    name: registry
  main:
    allow-bean-definition-overriding: true
  security:
    user:
      name: joshua
      password: joshua
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://joshua:joshua@localhost:8761/eureka/
logging:
  level:
    com.netflix:
      eureka: DEBUG
      discovery: OFF
