spring:
  application:
    name: keymaker
  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
  security:
    basic:
      enable: false
server:
  port: 8086
keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: joshua
      password: joshua
      realmImportFile: whoppr-realm.json
