spring:
  application:
    name: billing
  main:
    allow-bean-definition-overriding: true
security:
  oauth2:
    client:
      accessTokenUri: http://localhost:8086/auth/realms/whoppr/protocol/openid-connect/token
      userAuthorizationUri: http://localhost:8086/auth/realms/whoppr/protocol/openid-connect/auth
      clientId: whoppr
      clientSecret: whoppr-secret
      grantType: client_credentials
    resource:
      userInfoUri:  http://localhost:8086/auth/realms/whoppr/protocol/openid-connect/userinfo
      tokenInfoUri: http://localhost:8086/auth/realms/whoppr/protocol/openid-connect/token/introspect
server:
  port: 8084
logging:
  level:
    com.whoppr.*: ERROR
    org.mongodb.*: ERROR
    org.springframework.*: ERROR
    org.springframework.data.mongodb.core.MongoTemplate: ERROR

eureka:
  client:
    serviceUrl:
      defaultZone: http://joshua:joshua@localhost:8761/eureka/
